"""
Live REAPER integration tests — require a running REAPER instance with reapy server.

Run with:
    python -m pytest tests/test_reapy_live.py --reaper -v

These tests verify that the snippets generated by path_gen actually work against
a real REAPER session with Vital loaded on track 0.
"""

import io
import json
import os
import random
import re
import subprocess
import sys
import wave
from contextlib import redirect_stdout
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent))

pytestmark = pytest.mark.reaper


@pytest.fixture(scope="module")
def reapy_fx():
    """Return the first FX on track 0 of the current REAPER project."""
    import reapy
    with reapy.inside_reaper():
        project = reapy.Project()
        assert len(project.tracks) > 0, "No tracks in REAPER project"
        track = project.tracks[0]
        assert len(track.fxs) > 0, "No FX on track 0"
        fx = track.fxs[0]
        assert "vital" in fx.name.lower(), f"Expected Vital on track 0, got: {fx.name}"
    return True  # fixture just validates setup


@pytest.fixture(scope="module")
def path_iter():
    """Generate one path and return its first iteration."""
    from maestro.synth.path_gen import generate_preset_path
    rng = random.Random(99)
    result = generate_preset_path("lead", rng)
    return result["iterations"][0]


# ---------------------------------------------------------------------------
# Test 1: Search snippet executes and returns valid output
# ---------------------------------------------------------------------------

class TestSearchSnippet:
    def test_executes_without_error(self, reapy_fx, path_iter):
        import reapy
        snippet = path_iter["search_snippet"]
        # Execute in a controlled namespace with reapy context
        buf = io.StringIO()
        with reapy.inside_reaper():
            ns = {"reapy": reapy}
            exec(compile(snippet, "<search>", "exec"), ns)

    def test_output_format(self, reapy_fx, path_iter):
        """Each output line should be 'Param Name: 0.XXXX'."""
        import reapy
        snippet = path_iter["search_snippet"]
        lines = []
        # Capture print output by patching builtins.print in the exec namespace
        captured = []

        def fake_print(*args, **kwargs):
            captured.append(" ".join(str(a) for a in args))

        with reapy.inside_reaper():
            ns = {"reapy": reapy, "print": fake_print}
            exec(compile(snippet, "<search>", "exec"), ns)

        assert captured, "Search produced no output"
        for line in captured:
            assert ": " in line, f"Line missing ': ': {line!r}"
            val_str = line.rsplit(": ", 1)[1]
            val = float(val_str)
            assert 0.0 <= val <= 1.0, f"Value {val} out of [0,1] in line: {line!r}"

    def test_keyword_present_in_all_names(self, reapy_fx, path_iter):
        """All returned param names should contain the search keyword."""
        import reapy
        keyword = path_iter["search_keyword"]
        captured = []

        def fake_print(*args, **kwargs):
            captured.append(" ".join(str(a) for a in args))

        with reapy.inside_reaper():
            ns = {"reapy": reapy, "print": fake_print}
            exec(compile(path_iter["search_snippet"], "<search>", "exec"), ns)

        for line in captured:
            name = line.rsplit(": ", 1)[0]
            assert keyword in name.lower(), (
                f"keyword '{keyword}' not found in param name '{name}'"
            )


# ---------------------------------------------------------------------------
# Test 2: Set snippet actually changes param values in REAPER
# ---------------------------------------------------------------------------

class TestSetSnippet:
    def _get_params(self, param_names):
        """Read current normalized values for a list of display names."""
        import reapy
        values = {}
        with reapy.inside_reaper():
            fx = reapy.Project().tracks[0].fxs[0]
            for name in param_names:
                try:
                    values[name] = fx.params[name].normalized
                except Exception:
                    pass
        return values

    def _extract_set_params(self, action_snippet):
        """Extract {display_name: value} from action_snippet."""
        params = {}
        for match in re.finditer(r'fx\.params\["([^"]+)"\]\.value\s*=\s*([0-9.]+)',
                                  action_snippet):
            params[match.group(1)] = float(match.group(2))
        return params

    def test_params_change_after_set(self, reapy_fx, path_iter):
        import reapy
        snippet = path_iter["action_snippet"]
        expected = self._extract_set_params(snippet)
        assert expected, "No fx.params assignments found in action_snippet"

        # Read before
        before = self._get_params(list(expected.keys()))

        # Execute set snippet
        with reapy.inside_reaper():
            ns = {"reapy": reapy}
            exec(compile(snippet, "<set>", "exec"), ns)

        # Read after
        after = self._get_params(list(expected.keys()))

        # At least some params should have changed
        changed = [k for k in expected if abs(after.get(k, -1) - expected[k]) < 0.01]
        assert len(changed) > 0, (
            f"No params reached expected values. Expected: {expected}, Got: {after}"
        )

    def test_normalized_values_match_params_applied(self, reapy_fx, path_iter):
        """Values in snippet should match params_applied within tolerance."""
        import reapy
        snippet = path_iter["action_snippet"]
        expected = self._extract_set_params(snippet)

        with reapy.inside_reaper():
            ns = {"reapy": reapy}
            exec(compile(snippet, "<set>", "exec"), ns)

        after = self._get_params(list(expected.keys()))
        for name, exp_val in expected.items():
            got = after.get(name)
            if got is not None:
                assert abs(got - exp_val) < 0.005, (
                    f"Param '{name}': expected {exp_val:.4f}, got {got:.4f}"
                )


# ---------------------------------------------------------------------------
# Test 3: reaper_render_probe.py produces a valid WAV at /tmp/probe.wav
# ---------------------------------------------------------------------------

class TestRenderProbe:
    def test_file_created(self, reapy_fx):
        out = Path("/tmp/probe.wav")
        if out.exists():
            out.unlink()

        result = subprocess.run(
            [sys.executable, "scripts/reaper_render_probe.py"],
            capture_output=True, text=True,
            cwd=str(Path(__file__).parent.parent),
        )
        assert result.returncode == 0, f"render_probe failed:\n{result.stderr}"
        assert out.is_file(), "/tmp/probe.wav not created"
        assert out.stat().st_size > 44, "WAV file too small (just a header?)"

    def test_valid_wav(self, reapy_fx):
        subprocess.run(
            [sys.executable, "scripts/reaper_render_probe.py"],
            capture_output=True,
            cwd=str(Path(__file__).parent.parent),
        )
        with wave.open("/tmp/probe.wav") as w:
            assert w.getnframes() > 0, "WAV has zero frames"
            assert w.getnchannels() in (1, 2)
            assert w.getframerate() > 0

    def test_stdout_message(self, reapy_fx):
        result = subprocess.run(
            [sys.executable, "scripts/reaper_render_probe.py"],
            capture_output=True, text=True,
            cwd=str(Path(__file__).parent.parent),
        )
        assert "probe.wav" in result.stdout


# ---------------------------------------------------------------------------
# Test 4: Full iteration cycle — search → set → render
# ---------------------------------------------------------------------------

class TestFullIterationCycle:
    def test_cycle_completes(self, reapy_fx, path_iter):
        """Run search → set → render in sequence without errors."""
        import reapy

        # Search
        with reapy.inside_reaper():
            ns = {"reapy": reapy}
            exec(compile(path_iter["search_snippet"], "<search>", "exec"), ns)

        # Set
        with reapy.inside_reaper():
            ns = {"reapy": reapy}
            exec(compile(path_iter["action_snippet"], "<set>", "exec"), ns)

        # Render
        result = subprocess.run(
            [sys.executable, "scripts/reaper_render_probe.py"],
            capture_output=True, text=True,
            cwd=str(Path(__file__).parent.parent),
        )
        assert result.returncode == 0
        assert Path("/tmp/probe.wav").is_file()


# ---------------------------------------------------------------------------
# Test 5: Search result matches live REAPER state (init preset)
# ---------------------------------------------------------------------------

class TestSearchResultMatchesLive:
    def test_param_names_present_in_live(self, reapy_fx, path_iter):
        """Param names from synthetic search_result should exist in live fx.params."""
        import reapy

        # Get live param names
        with reapy.inside_reaper():
            fx = reapy.Project().tracks[0].fxs[0]
            live_names = {p.name for p in fx.params}

        # Check synthetic result names against live
        result = path_iter["search_result"]
        if not result:
            pytest.skip("empty search result for this iteration")

        missing = []
        for line in result.splitlines():
            name = line.rsplit(": ", 1)[0]
            if name not in live_names:
                missing.append(name)

        # Allow up to 10% mismatch (heuristic display name vs actual REAPER name)
        total = len(result.splitlines())
        assert len(missing) / total < 0.10, (
            f"{len(missing)}/{total} synthetic names not found in live REAPER: {missing[:5]}"
        )
